# Generated by Django 4.2.7 on 2026-06-19 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='路线名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('creator', models.CharField(blank=True, max_length=100, null=True, verbose_name='创建人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '巡检路线',
                'verbose_name_plural': '巡检路线',
                'db_table': 'inspection_route',
            },
        ),
        migrations.CreateModel(
            name='InspectionRouteCage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='顺序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('cage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cage', verbose_name='网箱')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspection.inspectionroute', verbose_name='巡检路线')),
            ],
            options={
                'verbose_name': '巡检路线-网箱关联',
                'verbose_name_plural': '巡检路线-网箱关联',
                'db_table': 'inspection_route_cage',
                'ordering': ['order'],
                'unique_together': {('route', 'cage')},
            },
        ),
        migrations.AddField(
            model_name='inspectionroute',
            name='cages',
            field=models.ManyToManyField(related_name='routes', through='inspection.InspectionRouteCage', to='core.cage', verbose_name='包含的网箱'),
        ),
        migrations.CreateModel(
            name='InspectionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspector', models.CharField(max_length=100, verbose_name='巡检人')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('status', models.CharField(choices=[('pending', '待开始'), ('in_progress', '进行中'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=50, verbose_name='状态')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='inspection.inspectionroute', verbose_name='巡检路线')),
            ],
            options={
                'verbose_name': '巡检记录',
                'verbose_name_plural': '巡检记录',
                'db_table': 'inspection_record',
            },
        ),
        migrations.CreateModel(
            name='InspectionPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_time', models.DateTimeField(verbose_name='检查时间')),
                ('water_temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='水温(°C)')),
                ('salinity', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='盐度(‰)')),
                ('ph_value', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='pH值')),
                ('water_quality', models.CharField(blank=True, choices=[('excellent', '优秀'), ('good', '良好'), ('fair', '一般'), ('poor', '较差'), ('very_poor', '很差')], max_length=50, null=True, verbose_name='水质情况')),
                ('abnormal_condition', models.TextField(blank=True, null=True, verbose_name='异常情况')),
                ('has_abnormality', models.BooleanField(default=False, verbose_name='是否有异常')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('cage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspection_points', to='core.cage', verbose_name='网箱')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='inspection.inspectionrecord', verbose_name='巡检记录')),
            ],
            options={
                'verbose_name': '巡检点',
                'verbose_name_plural': '巡检点',
                'db_table': 'inspection_point',
            },
        ),
    ]
