# Generated by Django 4.2.7 on 2026-06-20 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inspection', '0002_inspector_fk_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspectionroute',
            name='creator',
        ),
        migrations.AddField(
            model_name='inspectionroute',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_routes', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
    ]
