# Generated by Django 4.2.7 on 2026-06-19 07:16

import disease.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MortalityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter', models.CharField(max_length=100, verbose_name='上报人')),
                ('report_time', models.DateTimeField(auto_now_add=True, verbose_name='上报时间')),
                ('mortality_count', models.IntegerField(verbose_name='死亡数量(尾)')),
                ('cause', models.CharField(choices=[('disease', '疾病'), ('predation', '敌害'), ('environment', '环境因素'), ('feeding', '投喂问题'), ('operation', '操作失误'), ('unknown', '原因不明'), ('other', '其他')], max_length=50, verbose_name='死亡原因')),
                ('image', models.ImageField(blank=True, null=True, upload_to=disease.models.mortality_image_upload_path, verbose_name='图片')),
                ('description', models.TextField(verbose_name='情况描述')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('resolved', '已解决'), ('closed', '已关闭')], default='pending', max_length=50, verbose_name='状态')),
                ('treated_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='处理人')),
                ('treatment_method', models.TextField(blank=True, null=True, verbose_name='处理方案')),
                ('treatment_time', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('is_anomaly', models.BooleanField(default=False, verbose_name='是否异常')),
                ('anomaly_score', models.FloatField(default=0.0, verbose_name='异常分数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('cage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mortality_reports', to='core.cage', verbose_name='网箱')),
            ],
            options={
                'verbose_name': '死亡上报',
                'verbose_name_plural': '死亡上报',
                'db_table': 'mortality_report',
                'ordering': ['-report_time'],
            },
        ),
        migrations.CreateModel(
            name='DiseaseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter', models.CharField(max_length=100, verbose_name='上报人')),
                ('report_time', models.DateTimeField(auto_now_add=True, verbose_name='上报时间')),
                ('disease_type', models.CharField(choices=[('bacterial', '细菌性疾病'), ('viral', '病毒性疾病'), ('parasitic', '寄生虫病'), ('fungal', '真菌性疾病'), ('nutritional', '营养性疾病'), ('environmental', '环境性疾病'), ('other', '其他')], max_length=50, verbose_name='病害类型')),
                ('severity', models.CharField(choices=[('mild', '轻微'), ('moderate', '中等'), ('severe', '严重'), ('critical', '危急')], max_length=50, verbose_name='严重程度')),
                ('image', models.ImageField(blank=True, null=True, upload_to=disease.models.disease_image_upload_path, verbose_name='图片')),
                ('description', models.TextField(verbose_name='病害描述')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('resolved', '已解决'), ('closed', '已关闭')], default='pending', max_length=50, verbose_name='状态')),
                ('treated_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='处理人')),
                ('treatment_method', models.TextField(blank=True, null=True, verbose_name='处理方案')),
                ('treatment_time', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('is_anomaly', models.BooleanField(default=False, verbose_name='是否异常')),
                ('anomaly_score', models.FloatField(default=0.0, verbose_name='异常分数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('cage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_reports', to='core.cage', verbose_name='网箱')),
            ],
            options={
                'verbose_name': '病害上报',
                'verbose_name_plural': '病害上报',
                'db_table': 'disease_report',
                'ordering': ['-report_time'],
            },
        ),
    ]
