# Generated by Django 4.2.7 on 2026-06-19 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeaArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='海区名称')),
                ('location', models.CharField(max_length=500, verbose_name='位置')),
                ('area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='面积(公顷)')),
                ('depth', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='平均水深(米)')),
                ('lat_min', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='纬度最小值')),
                ('lat_max', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='纬度最大值')),
                ('lng_min', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='经度最小值')),
                ('lng_max', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='经度最大值')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '海区',
                'verbose_name_plural': '海区',
                'db_table': 'core_seaarea',
            },
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('id_card', models.CharField(max_length=18, unique=True, verbose_name='身份证号')),
                ('scale', models.CharField(blank=True, max_length=100, null=True, verbose_name='养殖规模')),
                ('registration_date', models.DateField(blank=True, null=True, verbose_name='注册日期')),
                ('contact_info', models.TextField(blank=True, null=True, verbose_name='其他联系方式')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('sea_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farmers', to='core.seaarea', verbose_name='所属海区')),
            ],
            options={
                'verbose_name': '养殖户',
                'verbose_name_plural': '养殖户',
                'db_table': 'core_farmer',
            },
        ),
        migrations.CreateModel(
            name='Cage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='网箱编号')),
                ('location', models.CharField(max_length=500, verbose_name='位置')),
                ('capacity', models.IntegerField(default=0, verbose_name='容量(尾)')),
                ('species', models.CharField(blank=True, max_length=200, null=True, verbose_name='养殖品种')),
                ('stocking_date', models.DateField(blank=True, null=True, verbose_name='投放日期')),
                ('status', models.CharField(choices=[('normal', '正常'), ('maintenance', '维护中'), ('empty', '空置'), ('abnormal', '异常')], default='normal', max_length=50, verbose_name='状态')),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='面积(平方米)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('sea_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cages', to='core.seaarea', verbose_name='所属海区')),
            ],
            options={
                'verbose_name': '网箱',
                'verbose_name_plural': '网箱',
                'db_table': 'core_cage',
            },
        ),
        migrations.CreateModel(
            name='CageFarmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('cage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cage_farmers', to='core.cage', verbose_name='网箱')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cage_farmers', to='core.farmer', verbose_name='养殖户')),
            ],
            options={
                'verbose_name': '网箱-养殖户关联',
                'verbose_name_plural': '网箱-养殖户关联',
                'db_table': 'core_cagefarmer',
                'unique_together': {('cage', 'farmer')},
            },
        ),
    ]
