# Generated by Django 4.2.7 on 2026-06-20 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_remove_lat_lng_fields_and_area_maxdigits'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farmer_profile', to=settings.AUTH_USER_MODEL, verbose_name='关联用户'),
        ),
    ]
